### ISSUE TITLE
How to add shadow between sidebar panel and editor window

### ISSUE THREAD

**Issue by rahulpathakgit** [johansatge/sienna#2]
Hi,
I also use watson theme and it has this shadow between sidebar and main window. Can you tell me how to add this in Sienna.

![screenshot from 2017-01-05 14-07-38](https://cloud.githubusercontent.com/assets/10892516/21673796/aaa86716-d350-11e6-8fd5-b62d769f3dc8.png)

**Comment by johansatge** [comment]
Hi,

On the Watson theme, the shadow is drawn on the [background image](https://github.com/dennistimmermann/watson-theme/blob/a66d48fa20824e7e2570d0d9950d470f4397387e/images/sidebar-bg.png) of the sidebar:

![sidebar-bg](https://cloud.githubusercontent.com/assets/5699295/21699115/7de84562-d39a-11e6-8883-0ac22c54312b.png)

You can apply the same effect on Sienna by drawing a shadow on those images: [`assets/sidebar/bg.png`](https://github.com/johansatge/sienna/blob/e0b7e410875996b488c6aa24f3f264bcf4e9d197/assets/sidebar/bg.png) and [`assets/sidebar/bg@2x.png`](https://github.com/johansatge/sienna/blob/e0b7e410875996b488c6aa24f3f264bcf4e9d197/assets/sidebar/bg@2x.png).
