### ISSUE TITLE
Idea ( config )

### ISSUE THREAD

**Issue by DavidStrada** [johansatge/sienna#4]
Hey thanks for creating the theme I've been searching for a while!!

Would be great if you could add a config option to either increase/decrease tab size.

thanks!

**Comment by johansatge** [comment]
Hi,

thanks for your feedback!

I'm not sure this can be easily done in the theme itself (from what I know, theme settings are `boolean` only, so the option would be something like `sienna_big_tabs: true|false`, which is limited IMO)

What can be easily done instead, is overriding the needed theme properties, like this:

* Create an empty file named `Sienna.sublime-theme`, in `Packages/User` (`Sublime Text` → `Preferences` → `Browse Packages...`)
* Edit the file and insert the following content:

```json
[
    {
        "class": "tabset_control",
        "tab_height": 36,
    }
]
```

Save the file (restarting Sublime may be needed). It should look like this:

![image](https://cloud.githubusercontent.com/assets/5699295/23142361/dbd40d56-f7bb-11e6-9fc0-eabc5075aa07.png)

Adjust to your liking 😃  (all properties present in [Sienna.sublime-theme](https://github.com/johansatge/sienna/blob/master/Sienna.sublime-theme) can be modified with that method)

Does it answer your request? _(If so, feel free to close the issue)_

thx!

**Comment by DavidStrada** [comment]
Hi, Yeah that solves it, thanks. Bummer that only accepts booleans and not a value.

Thanks,
David
